<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DeepSeekMonitor</RootNamespace>
    <AssemblyName>DeepSeekMonitor</AssemblyName>
    <ApplicationIcon>Assets\whale.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Assets\whale.ico" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

</Project>
